- added libzypp.changes and libzypp.spec to SVN

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -8,11 +8,6 @@ SUBDIRS = zypp testsuite po doc
 
 ## ##################################################
 
-.PHONY: package
-
-package: dist
-
-
 #ACLOCAL_AMFLAGS = -I m4
 ACLOCAL_AMFLAGS =
 
@@ -21,3 +16,23 @@ pkgconfig_DATA = libzypp.pc
 
 EXTRA_DIST = mkinstalldirs
 #config.rpath
+
+## ##################################################
+
+.PHONY: package package-local check-up-to-date
+
+package: 	check-up-to-date package-local
+
+package-local:	dist-bzip2
+	@if [ `bunzip2 -c $(distdir).tar.bz2 | wc --bytes` = 0 ] ; then \
+		echo "Error: $(distdir).tar.bz2 is empty" ; \
+		exit 1 ; \
+	fi
+	rm -f package/*.tar.bz2
+	rm -f package/*~
+	rm -f package/*.bak
+	rm -f package/*.auto
+	mv $(distdir).tar.bz2 package/
+
+check-up-to-date:
+	cd $(srcdir) && ! LC_ALL=C svn status --show-updates --quiet | grep -v '^Status against revision'
